git:
  depth: false

language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - libboost-all-dev
      - libssl-dev
      - curl
before_install:
  - wget https://developer.nvidia.com/compute/cuda/10.0/Prod/local_installers/cuda-repo-ubuntu1404-10-0-local-10.0.130-410.48_1.0-1_amd64
  - sudo dpkg -i cuda-repo-ubuntu1404-10-0-local-10.0.130-410.48_1.0-1_amd64
  - sudo apt-key add /var/cuda-repo-10-0-local-10.0.130-410.48/7fa2af80.pub
  - sudo apt-get update
  - sudo apt-get install cuda
  - export TZ=Etc/GMT-3
  - wget "https://cmake.org/files/v3.13/cmake-3.13.3-Linux-x86_64.sh"
  - sudo sh cmake-3.13.3-Linux-x86_64.sh --skip-license --prefix=/usr
  - eval "CC=gcc-7 && CXX=g++-7"
env: 
  - BUILD_TYPE=Release OS_FOLDER=linux
script:
  - cmake -DCMAKE_BUILD_TYPE=Release -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda .
  - make -j4
before_script:
  - BEAM_VERSION="1.0.$(git rev-list HEAD --count)"
  - curl -sL https://raw.githubusercontent.com/travis-ci/artifacts/master/install | bash

after_success:
  # deploy using ftp server
  - BUILDS_SERVER_PATH=${BUILD_SERVER}/files/$TRAVIS_BRANCH/$(date +%Y.%m.%d)/$BUILD_TYPE/$OS_FOLDER
  - tar -cvzf cuda-miner-gminer-$BEAM_VERSION.tar.gz --directory=$HOME/build/BeamMW/beam-cuda-miner beam-cuda-miner

  # upload binaries to FTP
  - curl --retry 3 --ftp-create-dirs -T cuda-miner-gminer-$BEAM_VERSION.tar.gz $BUILDS_SERVER_PATH/

  # upload binaries to S3
  - artifacts upload --target-paths "$TRAVIS_BRANCH/$(date +%Y.%m.%d)/$BUILD_TYPE/$OS_FOLDER/" cuda-miner-gminer-$BEAM_VERSION.tar.gz
