version: '{build}'
image: Visual Studio 2017

environment:
  CUDACXX: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2\bin\nvcc.exe
  BOOST_ROOT: C:\Libraries\boost_1_69_0
  OPENSSL_ROOT_DIR: c:\beam-libs\openssl
  BUILD_SERVER:
    secure: l9RqB2YbSnNIKZqTwnd67BHAXvbjmpj9zcf+YQPi9zfzsVeSysaoLD7gy4gSMjWurk2JVHjRpviw4bBxUbu2sA==
  BUILD_CONFIG: Release
  matrix:
  - arch: Win64

before_build:
  - cmd: appveyor DownloadFile http://builds.beam-mw.com/files/libs/boost_1_69_0.7z
  - cmd: 7z x boost_1_69_0.7z -oC:\Libraries
  - cmd: git clone --depth=1 https://github.com/BeamMW/libs.git c:/beam-libs
  - cmd: appveyor DownloadFile https://developer.nvidia.com/compute/cuda/9.2/Prod2/local_installers2/cuda_9.2.148_win10 -FileName cuda.exe    
  - cmd: cuda.exe -s nvcc_9.2 nvprune_9.2 cublas_dev_9.2 cufft_dev_9.2 curand_dev_9.2 cusolver_dev_9.2 cusparse_dev_9.2 nvgraph_dev_9.2 npp_dev_9.2 nvrtc_dev_9.2 nvml_dev_9.2 visual_studio_integration_9.2
  - cmd: set PATH=%ProgramFiles%\NVIDIA GPU Computing Toolkit\CUDA\v9.2\bin;%ProgramFiles%\NVIDIA GPU Computing Toolkit\CUDA\v9.2\libnvvp;%PATH%
  - cmd: cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=%BUILD_CONFIG%

build_script:
  - cmake --build . --parallel --config %BUILD_CONFIG%

on_success:
- ps: $env:DATE=[TimeZoneInfo]::ConvertTimeBySystemTimeZoneId([DateTime]::UtcNow, "Belarus Standard Time").ToString('yyyy.MM.dd')
- ps: $env:TIME=[TimeZoneInfo]::ConvertTimeBySystemTimeZoneId([DateTime]::UtcNow, "Belarus Standard Time").ToString('HH:mm:ss')
- cmd: >-

    git rev-list HEAD --count > BEAM_VERSION_REVISION

    set /p BEAM_VERSION_REVISION=<BEAM_VERSION_REVISION

    set BEAM_VERSION=1.0.%BEAM_VERSION_REVISION%

    7z a c:/projects/beam-cuda-miner/%BUILD_CONFIG%/cuda-miner-gminer-%BEAM_VERSION%.zip c:/projects/beam-cuda-miner/%BUILD_CONFIG%/beam-cuda-miner.exe

    set BUILDS_SERVER_PATH=%BUILD_SERVER%/files/%APPVEYOR_REPO_BRANCH%/%DATE%/Release/win

    curl --retry 3 --ftp-create-dirs -T "c:/projects/beam-cuda-miner/%BUILD_CONFIG%/cuda-miner-gminer-%BEAM_VERSION%.zip" %BUILDS_SERVER_PATH%/    
